version: "3.3"
services:
        db:
                image: ysbt_db:latest
                volumes: 
                        - /var/lib/postgresql/data
                ports:
                        - "5432:5332"
                restart: always
        api:
                image: ysbt_api:latest
                depends_on:
                        - db
                ports:
                        - "8080:8080"
                restart: always

